apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: eventendpointmgr
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    metric: VIRTUAL_PROCESSOR_CORE
    use: CloudPakForIntegrationNonProduction
  manager:
    apic:
      jwks:
        endpoint: 'https://apic-clust-ca800313-platform-api-cp4i.apps.68b007a76cf4fcd364d2eb58.eu1.techzone.ibm.com/api/cloud/oauth2/certs'
    tls: 
      ui:
        secretName: default-cert-copy
      trustedCertificates:
        - secretName: letsencrypt-chain
          certificate: ca.crt
        - certificate: ca.crt
          secretName: apim-cpd
    authConfig:
      authType: INTEGRATION_KEYCLOAK
    storage:
      storageClassName: PATCHED_BY_KUSTOMIZE
      type: persistent-claim
    template:
      pod:
        spec:
          containers:
            - name: manager
              #env:
              #  - name: FULL_LOG_TRACE
              #    value: 'true'
              #  - name: EI_AUTH_OAUTH2_ADDITIONAL_SCOPES
              #    value: 'email,profile,offline_access'
              resources:
                limits:
                  cpu: '0.5'
                  memory: 512Mi
                requests:
                  cpu: '0.25'
                  memory: 256Mi
